Project/urls.py
from django.conf import settings
from django.conf.urls.static import \
    static  # para importar os arquivos estaticos na URL
from django.contrib import admin
from django.urls import include, path


#O Django agora irá redirecionar tudo o que entra em 'http://127.0.0.1:8000 /'para portfolio.urls e procurar por novas instruções lá.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

# name="projeto", name="home" e name="category" são 
# os nomes das URLs que serão usadas para identificar a View

urlpatterns = [
    path('', views.home, name="home"),
    # id dentro de <int:id> vai passar como parametro na função projects
    path('project/<int:id>/', views.projects, name="projeto"), 
    path('project/category/<int:category_id>/', views.category, name="category"), 
]

portfolio/models.py
from django.contrib.auth.models import \
    User  # User também é uma tabela na base de dados
from django.db import models


# Imaginar models como tabelas da base de dados.
class Category(models.Model):
    name = models.CharField(max_length = 65)

    # FAz retornar o nome das categorias lá pagina "admin" ao inves de aparecer object(1)
    def __str__(self):
        return self.name


class Portfolio(models.Model):
    title = models.CharField(max_length = 65)
    description = models.CharField(max_length = 165)
    slug = models.SlugField()
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    project_detail = models.TextField()
    project_detail_is_html = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True) #auto_now_add = gera uma data no momento da criação
    updated_at = models.DateTimeField(auto_now = True) #auto_now = atualiza o campo mudado
    is_published = models.BooleanField(default = False)
    cover = models.ImageField(upload_to='portfolio/covers/%y/%m/%d/' ,blank=True, default='')

    #RELAÇÃO ENTRE TABELAS

    #Se algum tipo de categoria for excluida, esse campo tbm será. Ao ser excluido o campo será setado com NULL
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True,blank=True, default= None) 

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) 

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import get_object_or_404, render

from portfolio.models import Category, Portfolio
from utils.portfolio.factory import make_portfolio

# conectar models e templates

def home(request):
    cards = Portfolio.objects.filter(is_published=True).order_by('-id')    
    return render(request, 'portfolio/pages/home.html', context={
        'portfolios':cards, 
    })

def category(request, category_id):
    category_cards = Portfolio.objects.filter(
        category__id = category_id, is_published=True
        )
    # função get_object_or_404 para obter a categoria específica com base no category_id. 
    categoria = get_object_or_404(Category, id=category_id)
    return render(request, 'portfolio/pages/category.html', context={
        'portfolios':category_cards,
        'category_title': categoria.name
    })

def projects(request, id):
    #Ao clicar no projeto vai direto para a pagina
    project = get_object_or_404(Portfolio, id=id, is_published=True)

    return render(request, 'portfolio/pages/projects_view.html', context={
        'portfolio': project,
        'is_detail_page': True, #Se a pagina for a pagina de um projeto o botão de "ver mais não vai existir"
        })

portfolio/templates/portfolio/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{category_title}} | {% endblock title %}

{% block content %}
<div  class="category_name container">
    <h2>
        {{category_title}}
    </h2>
</div>

<div class="main-content main-content-list container">

    {% for portfolio in portfolios %}
        <!-- Vai colocar o conteudo do arquivo "portfolio.html" no bloco do "base.html" -->
        {% include 'portfolio/partials/portfolio.html'%}
        
        {% endfor %}
    </div>
    {% endblock content %}
    

portfolio/templates/portfolio/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for portfolio in portfolios %}
        <!-- Vai colocar o conteudo do arquivo "portfolio.html" no bloco do "base.html" -->
        {% include 'portfolio/partials/portfolio.html'%}

    {% endfor %}
</div>
{% endblock content %}

portfolio/templates/portfolio/pages/projects_view.html
{% extends 'global/base.html' %}

{% block title %}{{portfolio.title}} | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    <!-- Vai colocar o conteudo do arquivo "projects.html" no bloco do "base.html" -->
    {% include 'portfolio/partials/portfolio.html' %}
</div>
{% endblock content %}

portfolio/templates/portfolio/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="" target="_blank" rel="noreferrer noopener">By Gabriela Zerbone</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

portfolio/templates/portfolio/partials/head.html
{% load static %}

    <!-- Font-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/fontawesome.min.css"
        integrity="sha512-cHxvm20nkjOUySu7jdwiUxgGy11vuVPE9YeK89geLMLMMEOcKFyS2i+8wo0FOwyQO/bL8Bvq1KMsqK4bbOsPnA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/solid.min.css"
        integrity="sha512-bdTSJB23zykBjGDvyuZUrLhHD0Rfre0jxTd0/jpTbV7sZL8DCth/88aHX0bq2RV8HK3zx5Qj6r2rRU/Otsjk+g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/brands.min.css"
        integrity="sha512-L+sMmtHht2t5phORf0xXFdTC0rSlML1XcraLTrABli/0MMMylsJi3XA23ReVQkZ7jLkOEIMicWGItyK4CAt2Xw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


    <!--Font Roboto Slab-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">


    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

portfolio/templates/portfolio/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <!-- esse "portfolio:" é o app_name do arquivo "urls.py" -->
            <a class="main-logo" href="{% url "portfolio:home" %} ">
                <i class="fas fa-solid fa-mug-hot main-logo-icon"></i>
                <span class="main-logo-test">Portifólio</span>
            </a>
        </h1>
    </div>
</header>

portfolio/templates/portfolio/partials/portfolio.html
<!-- O "portfolio." é uma variavel no laço FOR do arquivo HOME.HTML -->

{% load static %}
<div class="portfolio portfolio-list-item">
    <div class="portfolio-cover">
        {% if is_detail_page is True %}
            <div class="img_project_detail">
                {% if portfolio.cover %}
                <a href="{% url 'portfolio:projeto' portfolio.id %}" >
                    <img src="{{portfolio.cover.url}}">
                </a>
                {% else  %}
                <a href="{% url 'portfolio:projeto' portfolio.id %}" >
                    <img src="{%static 'portfolio/image/sem_imagem.png' %}">
                </a>
                {% endif %}
            </div>
            {% else %}
            <div class="img_not_detail">
                {% if portfolio.cover %}
                <a href="{% url 'portfolio:projeto' portfolio.id %}" >
                    <img src="{{portfolio.cover.url}}">
                </a>
                {% else  %}
                <a href="{% url 'portfolio:projeto' portfolio.id %}" >
                    <img src="{%static 'portfolio/image/sem_imagem.png' %}">
                </a>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <div class="portfolio-title-container">
        <h2 class="portfolio-title">{{portfolio.title}}</h2>
    </div>

    <div class="portfolio-author">
        {% if portfolio.author is not None %}
            <span class="portfolio-author-item">
                <i class="fas fa-user"></i>
                {% if portfolio.author.first_name  %}
                    {{portfolio.author.first_name}} {{portfolio.author.last_name}}
                {% else %}
                    {{portfolio.author.username}}
                {% endif %}
            </span>
        {% endif %}

        <span class="portfolio-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ portfolio.created_at}}
        </span>

        {% if portfolio.category is not None %}
            <span class="portfolio-author-item">
                <a href="" ></a>
                <a href="{% url 'portfolio:category' portfolio.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{portfolio.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>
    {% if portfolio.category is not None %}
        <div class="portfolio-projects">
            <div class="portfolio-status">
                <a href="{% url 'portfolio:category' portfolio.category.id %}">
                    <span class="portfolio-status-level status-color">{{portfolio.category.name}}</span>
                </a>
            </div>
            <p>{{ portfolio.description}}</p>
        </div>
    {% endif %}

    <!-- is_detail_page é True na função projects (Arquivo views.py) -->
    {% if is_detail_page is not True %}
    <footer class="portfolio-footer">
        <!-- esse "portfolio:" é o app_name do arquivo "urls.py" e o "portfolio.id" é o "portfolio" do views.py-->
        <a class="portfolio-read-more button button-dark button-full-width" href=" {% url "portfolio:projeto" portfolio.id%} ">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="project_detail">
            {% if portfolio.project_detail_is_html is True %}
                {{ portfolio.project_detail|safe}} <!-- Permitirá o texto ser HTML -->

            {% else %}
                {{ portfolio.project_detail|linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}
</div>

portfolio/templates/portfolio/partials/projects.html
<!-- NÃO ESTÁ SENDO USADA -->

{%load static %}

<div class="portfolio portfolio-list-item">
    <div class="portfolio-cover">
        <img src="{%static 'portfolio/image/c-img.png' %}">
    </div>
    <div class="portfolio-title-container">
        <h2 class="portfolio-title">C</h2>
    </div>

    <div class="portfolio-author">
        <span class="portfolio-author-item">
            <i class="fas fa-user"></i>
            Gabriela Zerbone
        </span>
        <span class="portfolio-author-item">
            <i class="fas fa-calendar-alt"></i>
            03/03/2023 às 17:27
        </span>

        <span class="portfolio-author-item">
            <a href="" ></a>
        </span>
    </div>

    <div class="portfolio-projects">
        <div class="portfolio-status">
            <span class="portfolio-status-level status-color">Intermediário</span>
        </div>
        <p>Utilização da linguagem em meio acadêmico, realizando alguns projetos de disciplinas com tal linguagem.</p>
    </div>
    <footer class="portfolio-footer">
        <a class="portfolio-read-more button button-dark button-full-width" href="/project/3/">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
</div>

portfolio/templates/portfolio/partials/search-bar.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>